name: Build Binaries

on: [push, pull_request]

jobs:
  deploy:
    name: Deploy
    needs: build_binaries
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Display structure of downloaded files
        run: |
          mv artifacts/posp-ubuntu-20.04/BatchProve ./posp_bin_linux-amd64
          rm -fr artifacts/posp-ubuntu-20.04
          ls -la artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            posp_bin_linux-amd64
  build_binaries:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Cancel previous runs on the same branch
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest
      - name: Build C/C++ binaries
        run: |
          cmake --version
          mkdir -p build && cd build
          cmake -DBUILD_PROOF_OF_SPACE_STATICALLY=ON ../
          cmake --build . -- -j 6
          ls -la
      - uses: actions/upload-artifact@v2
        with:
          name: posp-${{ matrix.os }}
          path: build/BatchProve
          if-no-files-found: error
